"""add_intelligence_models_fixed

Revision ID: cd81216830e7
Revises: 
Create Date: 2026-01-02 12:52:12.966720

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd81216830e7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dynamic_niches',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('centroid_vector', sa.JSON(), nullable=False),
    sa.Column('creator_count', sa.Integer(), nullable=True),
    sa.Column('cluster_id', sa.Integer(), nullable=True),
    sa.Column('cluster_radius', sa.Float(), nullable=True),
    sa.Column('cluster_density', sa.Float(), nullable=True),
    sa.Column('keywords', sa.JSON(), nullable=True),
    sa.Column('example_creators', sa.JSON(), nullable=True),
    sa.Column('first_discovered', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_updated', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('signal_count_7d', sa.Integer(), nullable=True),
    sa.Column('momentum', sa.Float(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dynamic_niches_label'), 'dynamic_niches', ['label'], unique=False)
    op.create_table('topic_history',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('topic_hash', sa.String(), nullable=False),
    sa.Column('topic_vector', sa.JSON(), nullable=False),
    sa.Column('representative_text', sa.String(), nullable=True),
    sa.Column('first_seen', sa.DateTime(), nullable=False),
    sa.Column('last_seen', sa.DateTime(), nullable=False),
    sa.Column('appearance_count', sa.Integer(), nullable=True),
    sa.Column('lifecycle_phase', sa.String(), nullable=True),
    sa.Column('saturation_score', sa.Float(), nullable=True),
    sa.Column('peak_date', sa.DateTime(), nullable=True),
    sa.Column('decline_rate', sa.Float(), nullable=True),
    sa.Column('source_platforms', sa.JSON(), nullable=True),
    sa.Column('momentum_history', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_topic_history_topic_hash'), 'topic_history', ['topic_hash'], unique=True)
    op.create_table('emotional_states',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('anxiety_level', sa.Float(), nullable=True),
    sa.Column('trust_level', sa.Float(), nullable=True),
    sa.Column('fatigue_level', sa.Float(), nullable=True),
    sa.Column('posts_last_7_days', sa.Integer(), nullable=True),
    sa.Column('posts_last_30_days', sa.Integer(), nullable=True),
    sa.Column('last_rest_day', sa.DateTime(), nullable=True),
    sa.Column('rest_days_last_30', sa.Integer(), nullable=True),
    sa.Column('preferred_rest_day', sa.Integer(), nullable=True),
    sa.Column('interaction_frequency', sa.JSON(), nullable=True),
    sa.Column('rapid_check_count', sa.Integer(), nullable=True),
    sa.Column('preference_volatility', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_emotional_states_user_id'), 'emotional_states', ['user_id'], unique=True)
    op.create_table('user_competitors',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('competitor_id', sa.String(), nullable=False),
    sa.Column('is_accepted', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('relevance_score', sa.Float(), nullable=True),
    sa.Column('differentiation_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'competitor_id', name='uq_user_competitor')
    )
    op.create_index(op.f('ix_user_competitors_competitor_id'), 'user_competitors', ['competitor_id'], unique=False)
    op.create_index(op.f('ix_user_competitors_user_id'), 'user_competitors', ['user_id'], unique=False)
    op.create_table('user_actions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('action_type', sa.String(), nullable=False),
    sa.Column('content_vector', sa.JSON(), nullable=True),
    sa.Column('recommendation_id', sa.Uuid(), nullable=True),
    sa.Column('context', sa.JSON(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('learning_weight', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['recommendation_id'], ['recommendations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_actions_action_type'), 'user_actions', ['action_type'], unique=False)
    op.create_index(op.f('ix_user_actions_timestamp'), 'user_actions', ['timestamp'], unique=False)
    op.create_index(op.f('ix_user_actions_user_id'), 'user_actions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_actions_user_id'), table_name='user_actions')
    op.drop_index(op.f('ix_user_actions_timestamp'), table_name='user_actions')
    op.drop_index(op.f('ix_user_actions_action_type'), table_name='user_actions')
    op.drop_table('user_actions')
    op.drop_index(op.f('ix_user_competitors_user_id'), table_name='user_competitors')
    op.drop_index(op.f('ix_user_competitors_competitor_id'), table_name='user_competitors')
    op.drop_table('user_competitors')
    op.drop_index(op.f('ix_emotional_states_user_id'), table_name='emotional_states')
    op.drop_table('emotional_states')
    op.drop_index(op.f('ix_topic_history_topic_hash'), table_name='topic_history')
    op.drop_table('topic_history')
    op.drop_index(op.f('ix_dynamic_niches_label'), table_name='dynamic_niches')
    op.drop_table('dynamic_niches')
    # ### end Alembic commands ###
