books = [
    {
        "id": 1,
        "title": "Think Python",
        "author": "Allen B. Downey",
        "publisher": "O'Reilly Media",
        "published_date": "2021-01-01",
        "page_count": 1234,
        "language": "English",
    },
    {
        "id": 2,
        "title": "Django By Example",
        "author": "Antonio Mele",
        "publisher": "Packt Publishing Ltd",
        "published_date": "2022-01-19",
        "page_count": 1023,
        "language": "English",
    },
    {
        "id": 3,
        "title": "Fluent Python",
        "author": "Luciano Ramalho",
        "publisher": "O'Reilly Media",
        "published_date": "2022-05-10",
        "page_count": 1014,
        "language": "English",
    },
    {
        "id": 4,
        "title": "Python Crash Course",
        "author": "Eric Matthes",
        "publisher": "No Starch Press",
        "published_date": "2019-06-20",
        "page_count": 544,
        "language": "English",
    },
    {
        "id": 5,
        "title": "Effective Python",
        "author": "Brett Slatkin",
        "publisher": "Addison-Wesley",
        "published_date": "2020-11-01",
        "page_count": 480,
        "language": "English",
    },
    {
        "id": 6,
        "title": "Automate the Boring Stuff with Python",
        "author": "Al Sweigart",
        "publisher": "No Starch Press",
        "published_date": "2020-04-14",
        "page_count": 592,
        "language": "English",
    },
    {
        "id": 7,
        "title": "Clean Code",
        "author": "Robert C. Martin",
        "publisher": "Prentice Hall",
        "published_date": "2008-08-01",
        "page_count": 464,
        "language": "English",
    },
    {
        "id": 8,
        "title": "Design Patterns",
        "author": "Erich Gamma",
        "publisher": "Addison-Wesley",
        "published_date": "1994-10-31",
        "page_count": 395,
        "language": "English",
    },
    {
        "id": 9,
        "title": "FastAPI for Beginners",
        "author": "William S. Vincent",
        "publisher": "Leanpub",
        "published_date": "2023-02-15",
        "page_count": 320,
        "language": "English",
    },
    {
        "id": 10,
        "title": "Learning SQL",
        "author": "Alan Beaulieu",
        "publisher": "O'Reilly Media",
        "published_date": "2020-03-10",
        "page_count": 408,
        "language": "English",
    },
    {
        "id": 11,
        "title": "Database Internals",
        "author": "Alex Petrov",
        "publisher": "O'Reilly Media",
        "published_date": "2019-10-15",
        "page_count": 376,
        "language": "English",
    },
    {
        "id": 12,
        "title": "System Design Interview",
        "author": "Alex Xu",
        "publisher": "Independently Published",
        "published_date": "2020-06-12",
        "page_count": 322,
        "language": "English",
    },
    {
        "id": 13,
        "title": "Grokking Algorithms",
        "author": "Aditya Bhargava",
        "publisher": "Manning",
        "published_date": "2016-05-01",
        "page_count": 256,
        "language": "English",
    },
    {
        "id": 14,
        "title": "The Pragmatic Programmer",
        "author": "Andrew Hunt",
        "publisher": "Addison-Wesley",
        "published_date": "2019-09-13",
        "page_count": 352,
        "language": "English",
    },
    {
        "id": 15,
        "title": "You Don't Know JS Yet",
        "author": "Kyle Simpson",
        "publisher": "O'Reilly Media",
        "published_date": "2020-01-28",
        "page_count": 278,
        "language": "English",
    },
]
